server:
  port: 8888
  servlet:
    context-path: /sb

spring:
  datasource:
    password: root
    username: root
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/test

  thymeleaf:
    encoding: UTF-8
    cache: false
    prefix: classpath:/templates/
    suffix: .html
  mvc:
    static-path-pattern: /**
  web:
    resources:
      static-locations: classpath:/templates,classpath:/static/

mybatis:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
    auto-mapping-behavior: full
    use-generated-keys: true
  type-aliases-package: com.cssl.pojo
